### ISSUE TITLE
Blank identifier "_" should not be assigned

### ISSUE THREAD

**Issue by VincenzoArceri** [UniVE-SSV/go-lisa#14]
On branch master (commit 5bec8870efb4d900e6526852ce032947c3a287ca), the black identifier is treated as any other normal variable, and in turn, is also assigned. For instance, let's consider the following fragment and let's analyze it with the ```Interval``` and ```FieldSensitivePointBasedHeap``` abstract domains.  

```
package main

func f() (int,int) {
		return 1,2
}

func main() {
    x, _ := f()
}
```

The analysis result for the ```main```function is

![Schermata 2021-07-10 alle 13 52 14](https://user-images.githubusercontent.com/3504323/125162030-0b840200-e186-11eb-95c0-21bc4dcde3b1.png)

where also the variable ```_``` is assigned. This should not happen. Moreover, @olivieriluca I would ask you if you can check (and write some tests about that) if the black identifier wrongly follows the same scoping logic of the other variables you have implemented. In particular, I think the anonymous variable should be never scoped, that is:

```
func main() {
    x, _ := f()
    _, y := f()
}
```
should be a legal function.

**Comment by olivieriluca** [comment]
The correct name variable "_" is blank identifier (https://golang.org/doc/effective_go#blank). Yes,  it should be never scoped

**Comment by VincenzoArceri** [comment]
Great, thanks!
